version: '3.4'

services:

  notifier-api:
    image: localhost:5000/notifier-api:v1
    environment:
      - "KAFKA_HOST=${kafka_server}"
      - "KAFKA_PORT=9092"
      - "KAFKA_TOPIC=notification"
    build:
      context: Notifier.Api
      dockerfile: ./Notifier.Api/Dockerfile
    expose:
      - "80"
    ports:
      - "5101:80"
    depends_on:
      - kafka_server

  notifier-worker:
    image: localhost:5000/notifier-worker:v1
    environment:
      - "KAFKA_HOST=${kafka_server}"
      - "KAFKA_PORT=9092"
      - "KAFKA_TOPIC=notification"
    build:
      context: Notifier.Worker
      dockerfile: ./Notifier.Worker/Dockerfile
    depends_on:
      - kafka_server

  zookeeper_server:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zookeeper_server
    container_name: zookeeper_server
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper_server:2888:3888

  kafka_server:
    image: confluentinc/cp-kafka:7.1.1
    hostname: kafka_server
    container_name: kafka_server
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka_server:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_server:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper_server